<a href="https://colab.research.google.com/github/lifeisbeautifu1/graduate-work/blob/main/Introduction_to_PyTorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.0.1+cu118


In [3]:
scalar = torch.tensor(7)
scalar

tensor(7)

In [7]:
scalar.ndim

0

In [4]:
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [5]:
vector.ndim

1

In [8]:
matrix = torch.tensor([[1, 2], [3, 4]])

In [9]:
matrix

tensor([[1, 2],
        [3, 4]])

In [10]:
matrix.ndim

2

In [11]:
matrix.shape

torch.Size([2, 2])

In [14]:
tensor = torch.tensor([[[1, 2, 3], [1, 2, 3], [1, 2, 3]], [[1, 2, 3], [1, 2, 3], [1, 2, 3]]])
tensor

tensor([[[1, 2, 3],
         [1, 2, 3],
         [1, 2, 3]],

        [[1, 2, 3],
         [1, 2, 3],
         [1, 2, 3]]])

In [15]:
tensor.shape

torch.Size([2, 3, 3])

### Random Tensors

In [16]:
random_tensor = torch.rand(3, 4)

In [17]:
random_tensor

tensor([[0.2296, 0.6096, 0.6372, 0.6062],
        [0.5942, 0.6529, 0.5581, 0.6178],
        [0.7053, 0.5290, 0.2944, 0.7155]])

In [18]:
random_image_tensor = torch.rand(size=(256, 256, 3))

In [19]:
random_image_tensor.ndim, random_image_tensor.shape

(3, torch.Size([256, 256, 3]))

Zeros and ones

In [20]:
zeros = torch.zeros(size=(3, 4))

In [21]:
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [22]:
ones = torch.ones(size=(3, 4))

In [23]:
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

Range


In [24]:
torch.range(0, 10)

<ipython-input-24-cf0dcdb325c8>:1: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch.range(0, 10)


tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [26]:
torch.arange(0, 10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Tensors datatypes


In [28]:
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None,
                               device=None,
                               requires_grad=False)

In [29]:
float_32_tensor.dtype

torch.float32

In [30]:
float_16_tensor = float_32_tensor.type(torch.float16)

In [31]:
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [32]:
float_16_tensor.dtype

torch.float16

### Tensor Operations

In [33]:
tensor = torch.tensor([1, 2, 3])

In [34]:
tensor + 10

tensor([11, 12, 13])

In [35]:
torch.matmul(tensor, tensor)

tensor(14)

In [45]:
vector = torch.rand(size=(1, 2))
vector

tensor([[0.7974, 0.7250]])

In [46]:
second_vector = torch.rand(size=(2, 1))
second_vector

tensor([[0.1067],
        [0.7642]])

In [47]:
vector @ second_vector

tensor([[0.6391]])

Changing shape of tensors

In [53]:
tensor = torch.tensor([[1, 2, 3]])
tensor

tensor([[1, 2, 3]])

In [54]:
tensor, tensor.T

(tensor([[1, 2, 3]]),
 tensor([[1],
         [2],
         [3]]))

In [55]:
tensor.shape, tensor.T.shape

(torch.Size([1, 3]), torch.Size([3, 1]))

In [61]:
x = torch.arange(0, 100).type(torch.float32)

In [62]:
torch.min(x)

tensor(0.)

In [63]:
torch.max(x)

tensor(99.)

In [64]:
torch.mean(x)

tensor(49.5000)

In [65]:
torch.sum(x)

tensor(4950.)

In [66]:
x.argmin()

tensor(0)

In [67]:
x.argmax()

tensor(99)

In [68]:
x = torch.arange(1.0, 10.)

In [69]:
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [70]:
x_reshaped = x.reshape(9, 1)

In [72]:
x, x_reshaped

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]),
 tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]))

In [73]:
x.shape, x_reshaped.shape

(torch.Size([9]), torch.Size([9, 1]))

In [74]:
x

tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [77]:
y = torch.arange(9, 0, -1)

In [78]:
y

tensor([9, 8, 7, 6, 5, 4, 3, 2, 1])

In [81]:
torch.stack([x, y])

tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [9., 8., 7., 6., 5., 4., 3., 2., 1.]])

In [82]:
torch.hstack([x, y])

tensor([1., 2., 3., 4., 5., 6., 7., 8., 9., 9., 8., 7., 6., 5., 4., 3., 2., 1.])

In [83]:
torch.vstack([x, y])

tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [9., 8., 7., 6., 5., 4., 3., 2., 1.]])

In [84]:
y.shape

torch.Size([9])

In [85]:
x = torch.zeros(1, 1, 2)

In [86]:
x

tensor([[[0., 0.]]])

In [87]:
x.shape

torch.Size([1, 1, 2])

In [91]:
x.squeeze().shape, x.squeeze()

(torch.Size([2]), tensor([0., 0.]))